############################################################################################
# Split Ntuple into Training and Testing Samples
############################################################################################
root -l CITHZZ/LeptonScaleAndResolution/Electrons/SplitElectronNtuples.C+




############################################################################################
# Training
############################################################################################
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/trainElectronEnergyRegression.C+'("/afs/cern.ch/work/s/sixie/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY_53X.Training.root","regression/weightFile_V00.root","V00",kTRUE)'
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/trainElectronEnergyRegression.C+'("/afs/cern.ch/work/s/sixie/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY_53X.Training.root","regression/weightFile_V01.root","V01",kTRUE)'
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/trainElectronEnergyRegression.C+'("/afs/cern.ch/work/s/sixie/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY_53X.Training.root","regression/weightFile_V02.root","V02",kTRUE)'


#Train 7TeV 42X MC
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/trainElectronEnergyRegression.C+'("root://eoscms//eos/cms/store/group/phys_egamma/emanuele/eleid/hcptrees/electorons_elereg_zee42X.root","/data/smurf/sixie/HZZ/regression/42X/weightFile_V00.root","V00",kTRUE)'
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/trainElectronEnergyRegression.C+'("root://eoscms//eos/cms/store/group/phys_egamma/emanuele/eleid/hcptrees/electorons_elereg_zee42X.root","/data/smurf/sixie/HZZ/regression/42X/weightFile_V01.root","V01",kTRUE)'
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/trainElectronEnergyRegression.C+'("root://eoscms//eos/cms/store/group/phys_egamma/emanuele/eleid/hcptrees/electorons_elereg_zee42X.root","/data/smurf/sixie/HZZ/regression/42X/weightFile_V02.root","V02",kTRUE)'



############################################################################################
# Apply Regression
############################################################################################
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/applyElectronEnergyRegression.C+'("/afs/cern.ch/work/s/sixie/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY_53X.Testing.root","/data1/sixie/ntuples/LeptonScaleAndResolution/Electrons/output/ElectronNtuples.Summer12DY_53X.Testing.root","/afs/cern.ch/work/s/sixie/public/HZZ4l/weights/ElectronRegressionWeights/53X/weightFile_V00.root","regression/targets_V00/","V00")'
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/applyElectronEnergyRegression.C+'("/afs/cern.ch/work/s/sixie/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY_53X.Testing.root","/data1/sixie/ntuples/LeptonScaleAndResolution/Electrons/output/ElectronNtuples.Summer12DY_53X.Testing.root","/afs/cern.ch/work/s/sixie/public/HZZ4l/weights/ElectronRegressionWeights/53X/weightFile_V01.root","regression/targets_V01/","V01")'
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/applyElectronEnergyRegression.C+'("/afs/cern.ch/work/s/sixie/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY_53X.Testing.root","/data1/sixie/ntuples/LeptonScaleAndResolution/Electrons/output/ElectronNtuples.Summer12DY_53X.Testing.root","/afs/cern.ch/work/s/sixie/public/HZZ4l/weights/ElectronRegressionWeights/53X/weightFile_V02.root","regression/targets_V02/","V02")'

############################################################################################
# Make Performance Plots
############################################################################################
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/s/sixie/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY_53X.Testing.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V00/ElectronEnergyRegression_targets_V00.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V01/ElectronEnergyRegression_targets_V01.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V02/ElectronEnergyRegression_targets_V02.root","V00","V01","V02","regression/PerformancePlots_DY/",0)'
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/s/sixie/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY_53X.Testing.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V00/ElectronEnergyRegression_targets_V00.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V01/ElectronEnergyRegression_targets_V01.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V02/ElectronEnergyRegression_targets_V02.root","V00","V01","V02","regression/PerformancePlots_DY/",1)'
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/s/sixie/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY_53X.Testing.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V00/ElectronEnergyRegression_targets_V00.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V01/ElectronEnergyRegression_targets_V01.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V02/ElectronEnergyRegression_targets_V02.root","V00","V01","V02","regression/PerformancePlots_DY/",2)'

root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/s/sixie/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY_53X.Testing.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V00/ElectronEnergyRegression_targets_V00.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V01/ElectronEnergyRegression_targets_V01.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V02/ElectronEnergyRegression_targets_V02.root","V00","V01","V02","regression/PerformancePlots_DY/",3)'
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/s/sixie/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY_53X.Testing.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V00/ElectronEnergyRegression_targets_V00.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V01/ElectronEnergyRegression_targets_V01.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V02/ElectronEnergyRegression_targets_V02.root","V00","V01","V02","regression/PerformancePlots_DY/",4)'
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/s/sixie/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY_53X.Testing.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V00/ElectronEnergyRegression_targets_V00.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V01/ElectronEnergyRegression_targets_V01.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V02/ElectronEnergyRegression_targets_V02.root","V00","V01","V02","regression/PerformancePlots_DY/",5)'

root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/s/sixie/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY_53X.Testing.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V00/ElectronEnergyRegression_targets_V00.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V01/ElectronEnergyRegression_targets_V01.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V02/ElectronEnergyRegression_targets_V02.root","V00","V01","V02","regression/PerformancePlots_DY/",6)'
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/s/sixie/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY_53X.Testing.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V00/ElectronEnergyRegression_targets_V00.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V01/ElectronEnergyRegression_targets_V01.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V02/ElectronEnergyRegression_targets_V02.root","V00","V01","V02","regression/PerformancePlots_DY/",7)'
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/rootlogon.C CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/s/sixie/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY_53X.Testing.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V00/ElectronEnergyRegression_targets_V00.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V01/ElectronEnergyRegression_targets_V01.root","/afs/cern.ch/work/s/sixie/public/releases/analysis/CMSSW_5_3_3_patch3/src/regression/targets_V02/ElectronEnergyRegression_targets_V02.root","V00","V01","V02","regression/PerformancePlots_DY/",8)'

