###########################################################################
## Plots the performance of the regression for different eta and pt bins ##
## replace the filenames and directories with your desired names	 ##
## plots for bins -1, 10, 1 thru 8, use only the ones you want		 ##
###########################################################################

root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/a/atakeda/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12HZZ4l.Testing.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V00.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V01.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V10.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V11.root", "V00", "V01", "V10", "V11", "plots_Summer12HZZ4l/", 0)'

root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/a/atakeda/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12HZZ4l.Testing.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V00.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V01.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V10.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V11.root", "V00", "V01", "V10", "V11", "plots_Summer12HZZ4l/", 1)'

root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/a/atakeda/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12HZZ4l.Testing.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V00.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V01.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V10.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V11.root", "V00", "V01", "V10", "V11", "plots_Summer12HZZ4l/", 2)'

root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/a/atakeda/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12HZZ4l.Testing.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V00.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V01.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V10.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V11.root", "V00", "V01", "V10", "V11", "plots_Summer12HZZ4l/", 3)'

root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/a/atakeda/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12HZZ4l.Testing.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V00.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V01.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V10.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V11.root", "V00", "V01", "V10", "V11", "plots_Summer12HZZ4l/", 4)'

root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/a/atakeda/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12HZZ4l.Testing.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V00.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V01.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V10.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V11.root", "V00", "V01", "V10", "V11", "plots_Summer12HZZ4l/", 5)'

root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/a/atakeda/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12HZZ4l.Testing.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V00.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V01.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V10.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V11.root", "V00", "V01", "V10", "V11", "plots_Summer12HZZ4l/", 6)'

root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/a/atakeda/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12HZZ4l.Testing.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V00.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V01.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V10.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V11.root", "V00", "V01", "V10", "V11", "plots_Summer12HZZ4l/", 7)'

root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/a/atakeda/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12HZZ4l.Testing.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V00.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V01.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V10.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V11.root", "V00", "V01", "V10", "V11", "plots_Summer12HZZ4l/", 8)'

root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/a/atakeda/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12HZZ4l.Testing.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V00.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V01.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V10.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V11.root", "V00", "V01", "V10", "V11", "plots_Summer12HZZ4l/", 10)'

root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionPerformanceComparison.C+'("/afs/cern.ch/work/a/atakeda/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12HZZ4l.Testing.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V00.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V01.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V10.root", "targets_Summer12HZZ4l/ElectronEnergyRegression_targets_V11.root", "V00", "V01", "V10", "V11", "plots_Summer12HZZ4l/", -1)'


###########################################################################
# Variance Plots
###########################################################################
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionVarianceComparison.C+'("/afs/cern.ch/work/a/atakeda/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY.Testing.root", "/afs/cern.ch/work/a/atakeda/public/release/CMSSW_5_2_4_patch1/src/targets_withVar_Summer12DY/ElectronEnergyRegression_targets_V00.root", "/afs/cern.ch/work/a/atakeda/public/release/CMSSW_5_2_4_patch1/src/targets_withVar_Summer12DY/ElectronEnergyRegression_targets_V01.root", "V00", "V01", "plots/", -1)'


root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionVarianceComparison_2D.C+'("/afs/cern.ch/work/a/atakeda/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY.Testing.root", "/afs/cern.ch/work/a/atakeda/public/release/CMSSW_5_2_4_patch1/src/targets_withVar_Summer12DY/ElectronEnergyRegression_targets_V00.root", "/afs/cern.ch/work/a/atakeda/public/release/CMSSW_5_2_4_patch1/src/targets_withVar_Summer12DY/ElectronEnergyRegression_targets_V01.root", "V00", "V01", "plots/", -1)'
root -l -b -q CITHZZ/LeptonScaleAndResolution/Electrons/plotRegressionVarianceComparison_2Dprofile.C+'("/afs/cern.ch/work/a/atakeda/public/LeptonScaleAndResolution/Electrons/ElectronNtuples.Summer12DY.Testing.root", "/afs/cern.ch/work/a/atakeda/public/release/CMSSW_5_2_4_patch1/src/targets_withVar_Summer12DY/ElectronEnergyRegression_targets_V00.root", "/afs/cern.ch/work/a/atakeda/public/release/CMSSW_5_2_4_patch1/src/targets_withVar_Summer12DY/ElectronEnergyRegression_targets_V01.root", "V00", "V01", "plots/", -1)'

